export const TOGGLE_THEME = 'TOGGLE_THEME';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const SET_USER_DATA = 'SET_USER_DATA';
export const OPEN_QUESTION_PAGE = 'OPEN_QUESTION_PAGE';
export const CLOSE_QUESTION_PAGE = 'CLOSE_QUESTION_PAGE';
